### ISSUE TITLE
automate pulling current (or specific) version of vinecopulib from tvatter's repo

### ISSUE THREAD

**Issue by slayoo** [tnagler/vinecopulib-R#2]

**Comment by tnagler** [comment]
I've also thought about this, but am not sure whether this is a good idea:
- Doing it manually makes me aware of all changes and reminds me to write an R interface for every new feature.
- There may be changes that do not work well with R and break the package.

**Comment by slayoo** [comment]
That's why I've mentioned "(or specific) version" in the title

Perhaps a good way to go would be to use a git submodule, see: https://github.com/blog/2104-working-with-submodules

**Comment by tnagler** [comment]
So I was looking how other R interfaces to C++ libs deal with this (most prominently, [RcppEigen](https://github.com/RcppCore/RcppEigen)). They also do it manually, mainly because they have to tweak the C++ code a little to work with R. For example, I'll have to place `Rcpp::checkUserInterrupt()` in the code, so that R users can interrupt a function while it's running. So I think, I'll keep doing it manually, even though it's less convenient and more error prone :/

**Comment by slayoo** [comment]
We could equip the library with some externally-configurable hooks so that users could inject such checkUserInterrupt() calls into the control flow without needing to modify the library.

**Comment by slayoo** [comment]
BTW, I guess the RcppEigen you've mentioned is a perfect example for why not to go this way - vide https://github.com/tvatter/vinecopulib/issues/31 :)!
